import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { Menu } from "~/components";
import { setFavorites } from "~/store/favorites";
import { CharactersTemplate } from "~/templates";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    const getStorageFavorites = localStorage.getItem("favorites");

    if (getStorageFavorites)
      dispatch(setFavorites(JSON.parse(getStorageFavorites)));
  }, []);

  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Menu />
      <CharactersTemplate />
    </>
  );
}
